#!/usr/bin/env python

import sys

from rqt_example_py.my_module import MyPlugin
from rqt_gui.main import Main

plugin = 'rqt_example_py'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
